camel:
  springboot:
    # The Camel context name
    name: CamelRestInurbe
  component:
    servlet:
      mapping:
        enabled: true
        context-path: /inurbe/*

# Binding health checks to a different port
# change actuator endpoints path
management:
  server:
    port: 8081

# disable all management enpoints except health
endpoints:
  enabled: false
  health:
    enabled: true



oracle:
  service:
    # The name of the service hosting the MySQL database server,
    # can be customized using the 'MYSQL_SERVICE_NAME' env variable to use a different service
    name:     oracle
    # The database to use, can be customized using the 'MYSQL_SERVICE_DATABASE' env variable
    database: NOTARIADO
    host: 172.27.0.11
    port: 1521
    username: SISFV_NEXPASS
    password: SISFV$2024
    service-name: inurbe.minvivienda.local

spring:
  # Spring JDBC configuration
  sql:
    init:
      username: ${oracle.service.username}
      password: ${oracle.service.password}
      platform: oracle
      mode: always
  datasource:
    username: ${oracle.service.username}
    password: ${oracle.service.password}
    #url: jdbc:oraclexxx:thin:@//${${oracle.service.name}.service.host}:${${oracle.service.name}.service.port}/${oracle.service.database}
    url: jdbc:oracle:thin:@//${${oracle.service.name}.service.host}:${${oracle.service.name}.service.port}/${oracle.service.service-name}
  main:
    allow-bean-definition-overriding: true

# The application configuration properties
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s
